name: terraform-tutorials-ci

on: [push, pull_request]

env:
#  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_ACCESS_KEY_ID: AKIAWTVT3K2VHZM3NUTQ
  AWS_SECRET_ACCESS_KEY: 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
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
           version: "0.12.15"
      - name: Set up Terraform
        uses: marocchino/setup-terraform@v1
        with:
          version: "0.12.15"
      - name: Build module 'aws-instance-first-script'
        run: cd terraform-git-example && terraform init && terraform validate && terraform plan 
